version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    environment:
      CASSANDRA_CLUSTER_NAME: SpringCassandraCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./:/docker-entrypoint-initdb.d/init.cql
    networks:
      - app-network

volumes:
  postgres_data:
  cassandra_data:

networks:
  app-network:
    driver: bridge